const fs = require("fs");
const path = require("path");
const { logger } = require("./filesystem");

function backupFile(targetPath) {
	if (!fs.existsSync(targetPath)) {
		return;
	}
	const timestamp = new Date().toISOString().replace(/[-:T.]/g, "").slice(0, 14);
	const backupName = `${path.basename(targetPath)}.${timestamp}.bak`;
	fs.copyFileSync(targetPath, path.join(path.dirname(targetPath), backupName));
}

function ensureDir(dir) {
	if (!fs.existsSync(dir)) {
		fs.mkdirSync(dir, { recursive: true });
	}
}

function sanitizeShortLabel(label) {
	if (!label) {
		return "MOD";
	}
	return label.replace(/\s+/g, "").replace(/[^A-Z0-9]/gi, "").slice(0, 6).toUpperCase();
}

function normalizeLoadout(loadout, fallbackDescription) {
	if (!loadout) {
		return {
			name: "Clean Ferry",
			items: [],
			enabled: true,
			code: "Clean Ferry",
			roles: ["No task"],
			description: fallbackDescription || "Autogenerated loadout"
		};
	}
	const items = Array.isArray(loadout.items)
		? loadout.items.map((item) => ({
				name: item?.name || item?.CLSID || "Item",
				quantity: item?.quantity !== undefined ? item.quantity : item?.count || 0
		  }))
		: [];
	const roles = Array.isArray(loadout.roles) ? loadout.roles.filter(Boolean) : [];
	return {
		name: loadout.name || "Custom Loadout",
		items,
		enabled: loadout.enabled !== false,
		code: loadout.code || loadout.name || "Custom Loadout",
		roles: roles.length ? roles : ["No task"],
		description: loadout.description || fallbackDescription || ""
	};
}

function buildJsonEntry(descriptor) {
	const label = descriptor.displayName || descriptor.id;
	const shortLabel = sanitizeShortLabel(descriptor.shortName || label);
	const length = descriptor.length || 0;
	const loadouts = (descriptor.loadouts || []).map((loadout) => normalizeLoadout(loadout, label));
	return {
		name: descriptor.id,
		coalition: descriptor.coalition || "blue",
		era: descriptor.era || "Modern",
		category: descriptor.category ? descriptor.category.toLowerCase() : "aircraft",
		label,
		shortLabel,
		filename: descriptor.icon || "",
		enabled: descriptor.enabled !== false,
		type: descriptor.type || "Aircraft",
		description: descriptor.description || `Autogenerated entry for ${label}.`,
		abilities: descriptor.abilities || "",
		canTargetPoint: descriptor.canTargetPoint !== undefined ? descriptor.canTargetPoint : true,
		canRearm: descriptor.canRearm !== undefined ? descriptor.canRearm : descriptor.folderType === "aircraft",
		length,
		loadouts: loadouts.length ? loadouts : [normalizeLoadout(null, label)],
		liveries: descriptor.liveries || {}
	};
}

function formatLuaString(value) {
	return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function writeGeneratedLua(targetPath, descriptors) {
	if (!descriptors.length) {
		if (fs.existsSync(targetPath)) {
			fs.unlinkSync(targetPath);
		}
		return;
	}

	const modsListLines = [];
	const payloadLines = [];
	const payloadFileLines = [];

	for (const descriptor of descriptors) {
		const category = descriptor.category || (descriptor.folderType === "tech" ? "Aircraft" : "Aircraft");
		modsListLines.push(`\t["${formatLuaString(descriptor.id)}"] = "${formatLuaString(category)}",`);
		if (descriptor.unitPayloadRelativePath) {
			payloadFileLines.push(`\t["${formatLuaString(descriptor.id)}"] = "${formatLuaString(descriptor.unitPayloadRelativePath)}",`);
		} else {
			payloadLines.push(`\t["${formatLuaString(descriptor.id)}"] = {`);
			payloadLines.push(`\t\t["Clean Ferry"] = {}`);
			payloadLines.push("\t},");
		}
	}

	const content = [
		"local generated = {}",
		"generated.modsList = {",
		...modsListLines,
		"}",
		"generated.payloadFiles = {",
		...payloadFileLines,
		"}",
		"generated.modsUnitPayloads = {",
		...payloadLines,
		"}",
		"return generated",
		""
	].join("\n");

	ensureDir(path.dirname(targetPath));
	backupFile(targetPath);
	fs.writeFileSync(targetPath, content, "utf-8");
}

function writeModsJson(jsonPath, descriptors, removedIds = []) {
	if (!fs.existsSync(jsonPath)) {
		throw new Error(`mods.json not found at ${jsonPath}`);
	}
	const raw = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
	const managedIds = new Set(descriptors.map((d) => d.id));
	for (const id of removedIds) {
		delete raw[id];
	}
	for (const id of managedIds) {
		delete raw[id];
	}
	for (const descriptor of descriptors) {
		raw[descriptor.id] = buildJsonEntry(descriptor);
	}
	backupFile(jsonPath);
	const sortedKeys = Object.keys(raw).sort();
	const sortedObj = {};
	for (const key of sortedKeys) {
		sortedObj[key] = raw[key];
	}
	fs.writeFileSync(jsonPath, JSON.stringify(sortedObj, null, 2));
}

function generateConfigs(options) {
	const { modsRoot, descriptors, removedIds = [] } = options;
	if (!modsRoot) {
		throw new Error("modsRoot is required");
	}
	const scriptsPath = path.join(modsRoot, "Services", "Olympus", "scripts");
	const databasesPath = path.join(modsRoot, "Services", "Olympus", "databases", "units");
	const luaTarget = path.join(scriptsPath, "mods_generated.lua");
	const jsonTarget = path.join(databasesPath, "mods.json");

	if (!descriptors || descriptors.length === 0) {
		writeGeneratedLua(luaTarget, []);
		if (removedIds && removedIds.length > 0) {
			writeModsJson(jsonTarget, [], removedIds);
		}
		return;
	}

	writeGeneratedLua(luaTarget, descriptors);
	writeModsJson(jsonTarget, descriptors, removedIds);
}

module.exports = {
	generateConfigs
};
