export var defaultSRSData = {
    ClientGuid: "",
    Name: "",
    Seat: 0,
    Coalition: 0,
    AllowRecord: false,
    RadioInfo: {
      radios: [
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
        {
          enc: false,
          encKey: 0,
          freq: 1.0,
          modulation: 3,
          secFreq: 1.0,
          retransmit: false,
        },
      ],
      unit: "",
      unitId: 0,
      iff: {
        control: 2,
        mode1: -1,
        mode2: -1,
        mode3: -1,
        mode4: false,
        mic: -1,
        status: 0,
      },
      ambient: { vol: 1.0, abType: "" },
    },
    LatLngPosition: { lat: 0.0, lng: 0.0, alt: 0.0 },
  };